import { useEffect, useState } from 'react';
import { Link, NavLink, Route, Routes, useNavigate } from 'react-router-dom';
import { api } from './api';

const demoProjects = [
  { _id: 'demo1', title: 'Canyon Courtyard House', type: 'Residential', location: 'Los Angeles, CA', description: 'A quiet hillside residence organized around daylight, framed views, and a protected central courtyard.' },
  { _id: 'demo2', title: 'Market Street Studio', type: 'Commercial', location: 'San Francisco, CA', description: 'Adaptive reuse turns a former warehouse into a flexible workplace with warm material accents.' },
  { _id: 'demo3', title: 'Desert Listening Room', type: 'Interiors', location: 'Joshua Tree, CA', description: 'An intimate music room shaped by acoustic surfaces, soft lighting, and crafted built-in furniture.' }
];

function Header({ user, logout }) {
  return <header><Link className="brand" to="/">ARCH<span>CONNECT</span></Link><nav>
    <NavLink to="/">Home</NavLink><NavLink to="/projects">Projects</NavLink><NavLink to="/inquiry">Start Inquiry</NavLink>
    {user ? <><NavLink to="/dashboard">Dashboard</NavLink><button className="text-button" onClick={logout}>Logout</button></> : <NavLink to="/login">Login</NavLink>}
  </nav></header>;
}
function Layout({ user, logout, children }) { return <><Header user={user} logout={logout}/><main>{children}</main><footer><div className="brand">ARCH<span>CONNECT</span></div><p>Thoughtful spaces. Clear collaboration.</p><p>© 2026 ArchConnect · Los Angeles, California</p></footer></>; }

function Home() { return <>
  <section className="hero"><p className="eyebrow">Architecture · Interiors · Research</p><h1>Spaces designed<br/>around <em>how life feels.</em></h1><p className="lede">ArchConnect brings project stories and client collaboration into one clear, modern experience.</p><div className="actions"><Link className="button" to="/projects">Explore Projects</Link><Link className="button secondary" to="/inquiry">Start an Inquiry</Link></div><div className="hero-shape"><span>01</span></div></section>
  <section className="statement"><p className="eyebrow">What we believe</p><h2>Good architecture is both precise and deeply personal.</h2><p>We work across homes, workplaces, and interiors—connecting material, climate, and everyday rituals.</p></section>
  <section className="process"><article><b>01</b><h3>Listen</h3><p>We begin with your needs, site, budget, and ambitions.</p></article><article><b>02</b><h3>Explore</h3><p>Options become spatial ideas through drawings and models.</p></article><article><b>03</b><h3>Deliver</h3><p>Clear coordination carries the concept into construction.</p></article></section>
  </>; }

function Projects({ projects, refresh, user }) {
  const [filter, setFilter] = useState('All'); const [search, setSearch] = useState('');
  const list = (projects.length ? projects : demoProjects).filter(p => (filter === 'All' || p.type === filter) && `${p.title} ${p.location}`.toLowerCase().includes(search.toLowerCase()));
  const remove = async id => { if (id.startsWith('demo') || !confirm('Delete this project?')) return; await api(`/projects/${id}`, { method: 'DELETE' }); refresh(); };
  return <section className="page"><p className="eyebrow">Selected work</p><div className="page-heading"><h1>Projects</h1><p>Explore work by project type or location.</p></div><div className="filters"><input aria-label="Search projects" placeholder="Search title or location" value={search} onChange={e=>setSearch(e.target.value)}/>{['All','Residential','Commercial','Interiors','Concept'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="project-grid">{list.map((p,i)=><article className="project-card" key={p._id}><div className={`project-image tone-${i%3}`} style={p.imageUrl ? { backgroundImage:`url(${p.imageUrl})` } : {}}><span>{String(i+1).padStart(2,'0')}</span></div><p className="eyebrow">{p.type} · {p.location}</p><h2>{p.title}</h2><p>{p.description}</p>{user && !p._id.startsWith('demo') && <button className="danger" onClick={()=>remove(p._id)}>Delete my project</button>}</article>)}</div></section>;
}

function Auth({ mode, setUser }) {
  const nav=useNavigate(); const [form,setForm]=useState({name:'',email:'',password:''}); const [message,setMessage]=useState('');
  const submit=async e=>{e.preventDefault();setMessage('');try{const u=await api(`/auth/${mode}`,{method:'POST',body:JSON.stringify(form)});setUser(u);nav('/dashboard');}catch(x){setMessage(x.message)}};
  return <section className="auth page"><div><p className="eyebrow">Member access</p><h1>{mode==='login'?'Welcome back':'Create account'}</h1><p>Use your account to add portfolio projects and manage your submissions.</p></div><form onSubmit={submit}>{mode==='signup'&&<label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>}<label>Email<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Password<input type="password" minLength="8" required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{message&&<p className="form-message error">{message}</p>}<button className="button" type="submit">{mode==='login'?'Log In':'Sign Up'}</button><p>{mode==='login'?<>New here? <Link to="/signup">Create an account</Link></>:<>Already registered? <Link to="/login">Log in</Link></>}</p></form></section>;
}

function Inquiry(){const empty={name:'',email:'',projectType:'',budget:'',timeline:'',message:''};const [form,setForm]=useState(empty);const [status,setStatus]=useState('');const submit=async e=>{e.preventDefault();try{const r=await api('/inquiries',{method:'POST',body:JSON.stringify(form)});setStatus(r.message);setForm(empty)}catch(x){setStatus(x.message)}};return <section className="page split"><div><p className="eyebrow">New project</p><h1>Tell us what you’re imagining.</h1><p>Share a few essentials. We will review the project and reply with useful next steps.</p></div><form onSubmit={submit}><label>Name *<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email *<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Project type *<select required value={form.projectType} onChange={e=>setForm({...form,projectType:e.target.value})}><option value="">Choose one</option><option>Residential</option><option>Commercial</option><option>Interiors</option><option>Concept</option></select></label><label>Estimated budget *<select required value={form.budget} onChange={e=>setForm({...form,budget:e.target.value})}><option value="">Choose a range</option><option>Under $250,000</option><option>$250,000–$1M</option><option>$1M–$5M</option><option>$5M+</option></select></label><label>Desired timeline *<input required placeholder="Example: Design begins January 2027" value={form.timeline} onChange={e=>setForm({...form,timeline:e.target.value})}/></label><label>Project notes *<textarea required rows="5" value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></label>{status&&<p className="form-message">{status}</p>}<button className="button">Submit Inquiry</button></form></section>}

function Dashboard({ user, refresh }) {const empty={title:'',type:'Residential',location:'',description:'',imageUrl:''};const [form,setForm]=useState(empty);const [msg,setMsg]=useState('');if(!user)return <section className="page"><h1>Protected page</h1><p>Please <Link to="/login">log in</Link> to add a project.</p></section>;const submit=async e=>{e.preventDefault();try{await api('/projects',{method:'POST',body:JSON.stringify(form)});setForm(empty);setMsg('Project published successfully.');refresh()}catch(x){setMsg(x.message)}};return <section className="page split"><div><p className="eyebrow">Studio dashboard</p><h1>Hello, {user.name}.</h1><p>Add a new portfolio project. Required fields are validated before MongoDB saves it.</p><Link to="/projects">View all projects →</Link></div><form onSubmit={submit}><label>Project title *<input required maxLength="100" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Project type *<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>Residential</option><option>Commercial</option><option>Interiors</option><option>Concept</option></select></label><label>Location *<input required value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label>Image URL (optional)<input type="url" value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})}/></label><label>Description *<textarea required rows="5" maxLength="800" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>{msg&&<p className="form-message">{msg}</p>}<button className="button">Publish Project</button></form></section>}

export default function App(){const [user,setUser]=useState(null);const [projects,setProjects]=useState([]);const refresh=()=>api('/projects').then(setProjects).catch(()=>setProjects([]));useEffect(()=>{api('/auth/me').then(setUser).catch(()=>{});refresh()},[]);const logout=async()=>{await api('/auth/logout',{method:'POST'});setUser(null)};return <Layout user={user} logout={logout}><Routes><Route path="/" element={<Home/>}/><Route path="/projects" element={<Projects projects={projects} refresh={refresh} user={user}/>}/><Route path="/inquiry" element={<Inquiry/>}/><Route path="/login" element={<Auth mode="login" setUser={setUser}/>}/><Route path="/signup" element={<Auth mode="signup" setUser={setUser}/>}/><Route path="/dashboard" element={<Dashboard user={user} refresh={refresh}/>}/><Route path="*" element={<section className="page"><h1>Page not found</h1><Link to="/">Return home</Link></section>}/></Routes></Layout>}
